---
# Source: traefik/templates/rbac/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: heroes-traefik
  labels:
    app.kubernetes.io/name: traefik
    helm.sh/chart: traefik-10.3.6
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: traefik
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: heroes-traefik
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: heroes
