apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opensearch-master
  namespace: argocd
spec:
  project: heroes
  source:
    repoURL: 'https://54.72.174.143/api/v4/projects/3/packages/helm/stable'
    targetRevision: HEAD # For Helm, this refers to the chart version.
    path: ''
    # helm specific config
    chart: opensearch
    helm:
      valueFiles:
        - master.yaml
  destination:
    name: ''
    namespace: heroes
    server: 'https://kubernetes.default.svc'
