apiVersion: v1
kind: Pod
metadata:
  name: printenv-test-pod
  namespace: heroes
spec:
  containers:
    - name: printenv-test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      envFrom:
      - secretRef:
          name: doit-priv-ca-cert
  restartPolicy: Never
