---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-worker-workflow
  namespace: heroes
  labels:
    app: rabbitmq-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-worker
  template:
    metadata:
      namespace: heroes
      labels:
        app: rabbitmq-worker
    spec:
      containers:
      - name: rabbitmq-worker-workflow
        image: gitlab.heroes.priv:5050/heroes/k8s-apps/rabbitmq-worker-workflow:latest
        args: [
          "workflow"
        ]
      imagePullSecrets:
        - name: heroes-registry-ro
