---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq-worker
  name: rabbitmq-worker-minio
  namespace: heroes
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
  - name: rabbitmq-worker
    port: 5672  # Default rabbitmq-server port
    protocol: TCP
    targetPort: 5672  # Default rabbitmq-server port
  - name: ssh
    port: 22
    protocol: TCP
    targetPort: 22
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: rabbitmq-worker
  type: ClusterIP
