---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgresql-server
  name: postgresql-server
  namespace: heroes
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgresql-server
  type: ClusterIP
