---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: keycloak
  namespace: heroes
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`keycloak.heroes.doit.priv`)
      services:
        - name: keycloak-server
          port: 8080
