---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: keycloak-server
  name: keycloak-server
  namespace: heroes
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
  - name: keycloak
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: keycloak-server
  type: ClusterIP
