---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fastapi-server
  name: fastapi-server
  namespace: heroes
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: fastapi-server
  type: ClusterIP
