---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio-server
  name: minio-server-mockuporg
  namespace: heroes
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ports:
  - name: server
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: console
    port: 9001
    protocol: TCP
    targetPort: 9001
  selector:
    app: minio-server
  type: ClusterIP